name: habitude_aplication
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: TitanOne
      fonts:
        - asset: assets/TitanOne-Regular.ttf

    - family: TitilliumWeb
      fonts:
        - asset: assets/TitilliumWeb-Regular.ttf

  assets:
   - assets/splash.png

  
